import { useEffect, useState } from 'react';
import { LoaderCircle } from 'lucide-react';
import { Modal } from '../../../shared/components/Modal/Modal';
import { Button } from '../../../shared/components/Button/Button';
import { Input } from '../../../shared/components/Input/Input';
import { Select } from '../../../shared/components/Select/Select';
import { Alert } from '../../../shared/components/Alert/Alert';
import { Loading } from '../../../shared/components/Loading/Loading';
import { appointmentsApi, doctorsApi, patientsApi } from '../../../core/api/services';
import { ApiError } from '../../../core/api/client';
import type { Appointment, Doctor, Patient } from '../../../core/api/types';

interface Props { isOpen: boolean; onClose: () => void; onCreated: (appointment: Appointment) => void; }
type FieldErrors = Partial<Record<'patient' | 'doctor' | 'schedule' | 'mode', string>>;
const active = (status?: string) => status?.toUpperCase() === 'ACTIVE';

export function AddAppointmentModal({ isOpen, onClose, onCreated }: Props) {
  const [patients, setPatients] = useState<Patient[]>([]); const [doctors, setDoctors] = useState<Doctor[]>([]);
  const [patientSearch, setPatientSearch] = useState(''); const [patientId, setPatientId] = useState<number>(); const [patientSearchOpen, setPatientSearchOpen] = useState(false);
  const [doctorId, setDoctorId] = useState(''); const [date, setDate] = useState(''); const [time, setTime] = useState('');
  const [mode, setMode] = useState<'ONLINE' | 'WALK_IN'>('ONLINE'); const [patientLoading, setPatientLoading] = useState(false); const [doctorLoading, setDoctorLoading] = useState(false);
  const [patientLoadError, setPatientLoadError] = useState<string>(); const [doctorLoadError, setDoctorLoadError] = useState<string>();
  const [errors, setErrors] = useState<FieldErrors>({}); const [submitError, setSubmitError] = useState<string>(); const [submitting, setSubmitting] = useState(false);
  function loadDoctors() { setDoctorLoading(true); setDoctorLoadError(undefined); doctorsApi.list({ size: 100, status: 'ACTIVE' }).then((page) => setDoctors(page.content.filter((doctor) => active(doctor.status)))).catch((cause) => setDoctorLoadError(cause instanceof ApiError ? cause.message : 'Could not load registered doctors.')).finally(() => setDoctorLoading(false)); }
  function loadPatients(term = '') { setPatientLoading(true); setPatientLoadError(undefined); patientsApi.list({ size: 20, query: term || undefined, status: 'ACTIVE' }).then((page) => setPatients(page.content.filter((patient) => active(patient.status)))).catch((cause) => setPatientLoadError(cause instanceof ApiError ? cause.message : 'Could not load registered patients.')).finally(() => setPatientLoading(false)); }
  useEffect(() => { if (!isOpen) return; setPatientSearch(''); setPatientId(undefined); setPatientSearchOpen(false); setDoctorId(''); setDate(''); setTime(''); setMode('ONLINE'); setErrors({}); setSubmitError(undefined); loadDoctors(); loadPatients(); }, [isOpen]);
  useEffect(() => { if (!isOpen || !patientSearchOpen || !patientSearch.trim()) return; const timer = window.setTimeout(() => loadPatients(patientSearch), 250); return () => window.clearTimeout(timer); }, [patientSearch, patientSearchOpen, isOpen]);
  function validate() { const next: FieldErrors = {}; if (!patientId) next.patient = 'Select a registered patient from the search results.'; if (!doctorId) next.doctor = 'Select a registered doctor.'; if (!date || !time) next.schedule = 'Choose a date and time.'; if (!mode) next.mode = 'Select an appointment mode.'; setErrors(next); return !Object.keys(next).length; }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSubmitError(undefined); if (!validate()) return; const scheduledAt = new Date(`${date}T${time}`).toISOString(); if (Number.isNaN(Date.parse(scheduledAt)) || new Date(scheduledAt) <= new Date()) { setErrors((current) => ({ ...current, schedule: 'Choose a future date and time.' })); return; } setSubmitting(true); try { const appointment = await appointmentsApi.book({ patientId, doctorId: Number(doctorId), scheduledAt, appointmentMode: mode }); onCreated(appointment); onClose(); } catch (cause) { const apiError = cause instanceof ApiError ? cause : undefined; const fields: FieldErrors = {}; apiError?.fieldErrors.forEach((entry) => { if (entry.field === 'patientId') fields.patient = entry.message; if (entry.field === 'doctorId') fields.doctor = entry.message; if (entry.field === 'scheduledAt') fields.schedule = entry.message; if (entry.field === 'appointmentMode') fields.mode = entry.message; }); setErrors((current) => ({ ...current, ...fields })); setSubmitError(apiError?.message ?? 'Could not book the appointment. Please try again.'); } finally { setSubmitting(false); } }
  const doctorOptions = doctors.map((doctor) => ({ value: String(doctor.id), label: `${doctor.fullName}${doctor.specialty ? ` (${doctor.specialty})` : ''}` }));
  const patientTerm = patientSearch.trim().toLocaleLowerCase();
  const visiblePatients = patientTerm ? patients.filter((patient) => `${patient.fullName} ${patient.patientCode}`.toLocaleLowerCase().includes(patientTerm)) : patients;
  return <Modal isOpen={isOpen} onClose={onClose} title="Add appointment" description="Select registered people and reserve an available slot." size="md" footer={<><Button variant="ghost" onClick={onClose} disabled={submitting}>Cancel</Button><Button type="submit" form="add-appointment-form" isLoading={submitting} disabled={submitting || patientLoading || doctorLoading}>Book appointment</Button></>}><form id="add-appointment-form" onSubmit={submit} style={{ display: 'grid', gap: 'var(--mf-space-4)' }}>
    {submitError && <Alert tone="danger" title="Appointment could not be saved">{submitError}</Alert>}
    <div style={{ position: 'relative' }}><Input label="Patient *" value={patientSearch} placeholder="Search registered patients" error={errors.patient} aria-busy={patientLoading} rightIcon={patientLoading ? <LoaderCircle className="mf-field__search-spinner" size={16} aria-hidden="true" /> : undefined} onFocus={() => setPatientSearchOpen(true)} onClick={() => setPatientSearchOpen(true)} onChange={(event) => { setPatientSearch(event.target.value); setPatientSearchOpen(true); setPatientId(undefined); setErrors((current) => ({ ...current, patient: undefined })); }} /><small style={{ color: 'var(--mf-text-muted)' }}>{patientId ? 'Registered patient selected.' : 'Typed text is not submitted; choose a result.'}</small>{patientSearchOpen && (patientLoadError ? <Alert tone="danger" title="Could not load patients"><Button size="sm" variant="outline" type="button" onClick={() => loadPatients(patientSearch)}>Try again</Button></Alert> : <div role="listbox" aria-label="Matching registered patients" style={{ position: 'absolute', top: 'calc(100% + 4px)', left: 0, right: 0, zIndex: 20, maxHeight: 150, overflow: 'auto', background: 'var(--mf-surface)', border: '1px solid var(--mf-border-strong)', borderRadius: 'var(--mf-radius-sm)', boxShadow: 'var(--mf-shadow-md)' }}>{visiblePatients.length ? visiblePatients.map((patient) => <button type="button" role="option" aria-selected={patientId === patient.id} key={patient.id} onClick={() => { setPatientId(patient.id); setPatientSearch(`${patient.fullName} (${patient.patientCode})`); setPatientSearchOpen(false); setErrors((current) => ({ ...current, patient: undefined })); }} style={{ display: 'block', width: '100%', textAlign: 'left', padding: 8, border: 0, background: patientId === patient.id ? 'var(--mf-teal-50)' : 'transparent', cursor: 'pointer' }}>{patient.fullName} <small>({patient.patientCode})</small></button>) : <p role="status" style={{ margin: 8, color: 'var(--mf-text-muted)' }}>{patientLoading ? 'Searching registered patients…' : 'No registered patients match this search.'}</p>}</div>)}</div>
    {doctorLoading ? <Loading label="Loading registered doctors…" /> : doctorLoadError ? <Alert tone="danger" title="Could not load doctors"><Button size="sm" variant="outline" type="button" onClick={loadDoctors}>Try again</Button></Alert> : <Select label="Doctor *" value={doctorId} placeholder={doctorOptions.length ? 'Select a registered doctor' : 'No eligible doctors available'} options={doctorOptions} error={errors.doctor} disabled={!doctorOptions.length} onChange={(event) => { setDoctorId(event.target.value); setErrors((current) => ({ ...current, doctor: undefined })); }} />}
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--mf-space-3)' }}><Input label="Schedule date *" type="date" value={date} error={errors.schedule} onChange={(event) => setDate(event.target.value)} /><Input label="Schedule time *" type="time" value={time} onChange={(event) => setTime(event.target.value)} /></div><Select label="Mode *" value={mode} options={[{ value: 'ONLINE', label: 'Online' }, { value: 'WALK_IN', label: 'Walk in' }]} error={errors.mode} onChange={(event) => setMode(event.target.value as 'ONLINE' | 'WALK_IN')} />
  </form></Modal>;
}
